Strings = {
    activity: "ACTIVITY",
    notification: "NOTIFICATION",
    init: "INIT",
    success: "success",
    contentType: "text/xml; charset=\"utf-8\" ",
    type: "POST",
    dataType: "xml",
    soapTokenElement: "tokenws\\:token",
    token: "token",
    tokenServiceUrl: "/axis2/services/TokenService?wsdl",
    taskManagementServiceUrl: "/axis2/services/TaskManagementServices?wsdl",
    soapTaskElement: "tms\\:task",
    soapTaskIdElement: "tms\\:taskId",
    soapTaskStateElemet: "tms\\:taskState",
    soapTaskTypeElement: "tms\\:taskType",
    soapTaskDescriptionElement: "tms\\:description",
    soapFormUrlElement: "tms\\:formUrl",
    soapCrtnDtElement: "tms\\:creationDate",
    defaultUser: "intalio\\admin",
    strFalse: "false",
    PATask: "PATask",
    notificationLwrCs: "Notification",
    PIPATask: "PIPATask",
    mainPageId: "mainPage",
    loginPageId: "loginPage",
    subQueryTaskStateRdy: "T._state = TaskState.READY",
    loginPageUrl: "/TaskManager/Login/Login.html",
    mainPageUrl: "../"
};